language: go

go:
  - 1.8.x

go_import_path: github.com/BjornGudmundsson/p2pBackup/kyber

install:
  - go get -t ./...
  - go get github.com/dedis/Coding || true

script:
  - make test_stable

notifications:
  email: false
